CREATE TABLE words (
    id SERIAL PRIMARY KEY,
    word TEXT NOT NULL,
    index INT NOT NULL,
    DELIVERED BOOLEAN DEFAULT FALSE,
    DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_DELIVERED TIMESTAMP,
    WHO_DELIVERED TEXT NOT NULL
);